language: ruby

branches:
  only:
  - master

before_install:
- gem install jekyll
- gem install rdiscount

install:
#- bundle install

before_script:
- git config --global user.name 'Kyle M Hall'
- git config --global user.email 'kyle@bywatersolutions.com'

script:
# Short circuite infinite loop of site updating
- jekyll build -d docs
- git add docs
- git status
- git commit --allow-empty -m 'Site auto-updated [ci skip]'
- git status
- git remote add github https://$GH_TOKEN@github.com/kylemhall/libki.org.git
- git push github HEAD:master
