title: Libki Kiosk Management System
author: Kyle M Hall
email: kyle@libki.org
description: > # this means to ignore newlines until "baseurl:"
  Libki is a cross-platform Open Source computer reservation & time management system.

twitter_username: LibkiLMS
github_username:  Libki

sass:
    style: compressed
